---
- name: Configure NTP
  hosts: vmx_devices
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
   - name: USERNAME
     prompt: User name
     private: no
   - name: DEVICE_PASSWORD
     prompt: Device password
     private: yes

  tasks:
   - name: Load the NTP server configuration
     juniper_junos_config:
       user: "{{ USERNAME }}"
       passwd: "{{ DEVICE_PASSWORD }}"
       config_mode: exclusive
       load: replace
       lines:
         - <configuration>
         -   <system>
         -     <ntp replace="replace">
         -       <server>
         -         <name>{{ ntp_server }}</name>
         -       </server>
         -     </ntp>
         -   </system>
         - </configuration>
       format: xml
       commit: true
     register: response

   - name: Print the config diff     
     debug:
       var: response.diff_lines
