---
- name: Retrieve vMX-1 interfaces configuration
  hosts: vMX-1
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
   - name: USERNAME
     prompt: User name
     private: no
   - name: DEVICE_PASSWORD
     prompt: Device password
     private: yes

  tasks:
   - name: Retrieve the committed configuration
     juniper_junos_config:
       user: "{{ USERNAME }}"
       passwd: "{{ DEVICE_PASSWORD }}"
       retrieve: committed
       filter: interfaces
     register: response

   - name: Print the lines in the config
     debug:
       var: response.config_lines

